# Generated by Django 6.0.6 on 2026-07-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('seguridad', 'Herramientas de Seguridad'), ('lenguajes', 'Lenguajes de Programación'), ('redes', 'Redes'), ('web', 'Tecnologías Web')], max_length=20)),
                ('icono', models.ImageField(upload_to='habilidades/')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
                'ordering': ['categoria', 'orden'],
            },
        ),
    ]
