# Generated by Django 6.0.6 on 2026-07-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_habilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='icono',
            field=models.CharField(help_text='Nombre del archivo en static/img/skills/, ej: python.png', max_length=100),
        ),
    ]
