# Generated by Django 6.0.6 on 2026-07-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('resumen', models.CharField(help_text='Aparece en el listado', max_length=250)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(help_text='Ej: SOC, Pentesting, Redes, CTF', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('publicado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
